-- Diplomacy
NDefines.NDiplomacy.VASSAL_LIMIT_KING_MULT = 30.0       -- up from 20
NDefines.NDiplomacy.VASSAL_LIMIT_EMPEROR_MULT = 40.0    -- up from 30
NDefines.NDiplomacy.CONCLAVE_VASSAL_LIMIT_KING_MULT = 25.0
NDefines.NDiplomacy.CONCLAVE_VASSAL_LIMIT_EMPEROR_MULT = 35.0
NDefines.NDiplomacy.MAX_PREP_INV_TARGET_HOLDINGS = 60   -- up from 40
NDefines.NDiplomacy.MAX_PREP_INV_ATTACKER_HOLDINGS = 60 -- up from 40

-- Military
NDefines.NMilitary.SHATTERED_RETREAT_MAX_PROVINCES = 6 -- reduced max by 1 from EMF+SWMH v8.06

-- Engine

NDefines.NEngine.MISSING_SCRIPTED_SUCCESSOR_ERROR_CUTOFF_YEAR = 1018
NDefines.NEngine.MISSING_SCRIPTED_SUCCESSOR_ERROR_CUTOFF_MONTH = 1
NDefines.NEngine.MISSING_SCRIPTED_SUCCESSOR_ERROR_CUTOFF_DAY = 1

-- AI
NDefines.NAI.COALITION_PROVINCE_MULTIPLIER = 0.7 -- down from 1.0
